[project]
name = "vega"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "pyahocorasick>=2.3.1",
    "pydantic-settings>=2.15.0",
]

[project.optional-dependencies]
router = ["fastapi", "pydantic", "uvicorn", "pyahocorasick", "aiohttp", "pydantic-settings"]
shared = ["pydantic", "rich"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/vega"]

[dependency-groups]
dev = [
    "ruff>=0.16.6",
    "ty>=0.0.78",
]
